#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=TrainPLC
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:30:00
#SBATCH --output=./logs/job_outputs/slurm_output_%A.out

module purge
module load 2024

source .env
source .venv/bin/activate

python -m src.experiments.gbif_hyperbolic.evaluation.main \
    --n_shot 5 \
    --n_way 1 \
    --n_query 15 \
    --run_id ff72d8ced7aa4b7e93ca964e2cc07c48 \
    --prototypes avg_multi
