#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=TrainPrototypes
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=3:00:00
#SBATCH --output=./logs/job_outputs/slurm_output_%A.out

module purge
module load 2024

source .env
source .venv/bin/activate

python -m src.experiments.gbif_hyperbolic.prototypes.distortion --dims 128 -d gbif_coleoptera_hierarchical_full
